.gitignore
client/src/components/AuthUserSession/withAuthentication.js
client/src/pages/Login/Login.js
package.json
server.js
yarn.lock

add initial token verification to the server side.  also create basic login form.

Firebase admin

---

client/src/components/NavLoggedIn/NavLoggedIn.js
client/src/pages/Join/Join.js
client/src/pages/Login/Login.js

also, signout link now points to home

Add redirect on successful login/signup

---

server.js

Super basic api routes for creating and retrieving posts.

initial post api routes

---

controllers/StoryController.js
controllers/bitcoinStoryController.js
controllers/commentController.js
controllers/postController.js
routes/api/index.js
routes/index.js
server.js

Refactored post routes into separate routes and controllers.  Also added routes for comments.
All of these are still very basic and do not check for authentication.

Post routes & Comment routes

---

client/src/components/Nav/Nav.css
client/src/components/Nav/Nav.js
client/src/components/NavLoggedIn/NavLoggedIn.js
client/src/components/NavNotLoggedIn/NavNotLoggedIn.js
client/src/components/Typwriter/Typwriter.css
scripts/categorySeed.js

Fixed the Nav Toggler
Added Nav Toggler animation
Added Category seeds

Poststyling

---

client/package.json
client/src/components/PostComponents/PostDetail/PostDetail.js
client/src/components/TipButton/TipButton.js
client/src/components/TipButton/index.js
client/src/pages/Content/Content.js
client/yarn.lock
package-lock.json
scripts/userSeed.js

Implemented the PayButton component.  Added to the PostDetail component to allow upvoting.  Right now it just flags an alert after a successful payment and pays only a fixed amount (.03), but I'll add custom tip amounts and record them in the database next.

Basic functional pay button

---

client/src/components/PostComponents/PostDetail/PostDetail.js

Submit valid tip amount, and then money button will appear.

Added custom tip amount.  

---

client/src/App.js
client/src/components/PostComponents/PostListDisplay/PostListItem.js
client/src/components/Stickybar/Stickybar.js
client/src/components/TipButton/TipButton.js
client/src/index.css
client/src/pages/Content/Content.js
client/src/pages/CreatePost/CreatePost.js
client/src/pages/Home/Home.js
client/src/pages/MainCategoryPage/MainCategoryPage.js
client/src/utils/API.js
package-lock.json

Storypagefix

---

client/src/components/CommentDisplay/Comments.css
client/src/components/CommentDisplay/Comments.js
client/src/components/CommentDisplay/NestedComments.css
client/src/components/CommentDisplay/NestedComments.js
client/src/components/PostComponents/PostDetail/PostDetail.js
client/src/components/PostComponents/PostDetail/postDetail.css
client/src/components/PostComponents/PostForm/FormBtn.js
client/src/components/TipButton/TipButton.css
client/src/pages/Content/Content.js
client/src/pages/Content/content.css
client/src/pages/EditPage/EditPage.js
client/src/pages/EditPage/editpage.css

Formatting for display form and edit form
added links to authors

Editpostformatting

---

client/src/components/PostComponents/PostDetail/PostDetail.js
client/src/utils/API.js
models/Post.js
routes/api/postRouter-AUTH.js
scripts/postSeed.js

When user views a post, it will only be seen if the user is the author or a purchaser.  Otherwise, the teaser is shown with a purchase button.

Add paywall

---

client/src/App.js
client/src/pages/Editor/Editor.css
client/src/pages/Editor/Editor.js
client/src/pages/Editor/colourStyles.js
client/src/pages/Editor/index.js
client/src/utils/API.js
routes/api/postRouter-AUTH.js

Refactor create/edit post into one Editor Page

---

client/src/components/ListokaMoneyButton/ListokaMoneyButton.js
client/src/pages/Profile/Profile.js

Refactor ListokaMoneyButton to rely on less state and respond dynamically to prop changes.

Swap ListokaMoneyButton for MoneyButton on account page to enable tx logging

---

client/src/components/Comments/CommentList.js
client/src/components/Comments/CommentListContainer.js
client/src/components/Comments/CommentListHeader.js
client/src/components/Comments/CommentNode.js
client/src/components/Comments/CommentNodeContainer.js
client/src/components/Comments/CommentReplyForm.js
client/src/components/Comments/CommentVoteButton.js
client/src/components/VoteBasket/VoteBasket.js
client/src/components/Widgets/TextButton.js

Bigger change is factoring out `CommentListheader` functionality from the `CommentNode`, cleaning up the `CommentReplyForm` and factoring out the `TextButton` that is used throughout the comments and putting it into its own widget.

More Comment Tweaks

---

client/src/index.css
client/tailwind.js

tailwind additions

---

client/package.json
client/yarn.lock

We were using a really old one...  Now we have some more built-in functionality like css-modules.

update react-scripts to the latest version

---

client/src/components/Modals/ModalWrapper.js
client/src/components/Modals/withModals.js

fix modal close issue

---

client/src/components/Comments/CommentListContainer.js

only show votebasket if there are pending votes

---

client/src/pages/Content/ContentDetailContainer.js

automatically load post body after purchase

---

routes/api/userRouter-AUTH.js

closes #8 
The actual model itself doesn't actually check, but we verify both client side, and also server-side on the create user route.

verify username is unique on create route

---

client/src/pages/Main/MainPageContainer.js

Filtering by tags is now an 'AND' operation

---

client/src/components/List/DraftListItem.js

DraftListItem shows Untitled as needed

---

client/src/pages/Editor/EditorPageContainer.js

fix empty draft edit issue

---

client/package.json
client/src/components/ListokaMoneyButton/ListokaMoneyButton.js
client/src/components/Transactions/Transactions.js
client/src/components/Transactions/TxListItemDebit.js
client/src/css/tailwind.css
client/yarn.lock

updated packages and a few minor tweaks
